// AVH V3 — Router de módulos, auditoría y bindings de filtros.
async function markAllNotifications(){const r=await rpc('mark_notifications_read');if(r.error)return alert(r.error);await loadAll(true);renderModule('alerts')}
function renderAudit(){
  if(profile.role!=='admin')return;
  const users=new Map(D.profiles.map(x=>[x.id,x.username]));
  const actions={insert:'Creación',update:'Modificación',delete:'Eliminación',purchase_confirmed:'Compra confirmada',purchase_order_generated:'OC generada',purchase_item_updated:'Ítem de compra editado',purchase_item_split:'Ítem dividido por recepción',opening_inventory_opened:'Inventario inicial abierto',opening_inventory_closed:'Inventario inicial cerrado',opening_inventory_reopened:'Inventario inicial reabierto',opening_inventory_priced:'Stock inicial valorizado'};
  const detailText=v=>{
    if(v==null)return'';
    if(typeof v==='string')return v;
    try{return Object.entries(v).slice(0,5).map(([k,val])=>`${k}: ${typeof val==='object'?JSON.stringify(val):String(val)}`).join(' · ')}catch{return''}
  };
  const rows=(D.auditEvents||[]).slice(0,300);
  $('#moduleContent').innerHTML=`<div class="section-head"><div><h2>Auditoría</h2><p>Eventos reales registrados por backend</p></div><span class="badge green">${rows.length} eventos</span></div><div class="card"><div class="eyebrow">TRAZABILIDAD</div><div class="report-big">${rows.length} eventos cargados</div><div class="subtext">Fuente: audit_events. Los movimientos y cambios administrativos quedan separados del simple historial visual.</div></div><div class="section-head"><h2>Actividad reciente</h2></div><div class="list">${rows.map(e=>`<div class="row"><div class="line"><div><div class="title">${esc(actions[e.action]||e.action||'Evento')} · ${esc(e.entity_type||'sistema')}</div><div class="subtext">${esc(users.get(e.actor_id)||'Sistema')} · ${dt(e.created_at)}${e.warehouse_id?' · '+esc(whName(e.warehouse_id)):''}</div>${e.detail?`<div class="hint" style="margin-top:4px">${esc(detailText(e.detail))}</div>`:''}</div><span class="badge">${esc(e.action||'AUDIT')}</span></div></div>`).join('')||'<div class="empty">No hay eventos de auditoría visibles.</div>'}</div>`;
}
async function renderProductRequest(){$('#moduleContent').innerHTML=`<div class="section-head"><div><h2>Solicitar producto nuevo</h2><p>El administrador revisa y aprueba antes de incorporarlo al catálogo</p></div></div><div class="card"><div class="field"><label>Nombre del producto</label><input id="reqProdName" placeholder="Ej.: Disco flap 4 1/2"></div><div class="two"><div class="field"><label>Unidad base</label><select id="reqProdUnit">${unitOptions()}</select></div><div class="field"><label>Motivo / uso</label><input id="reqProdNotes" placeholder="Opcional"></div></div><button id="sendProdRequest" class="btn primary">Enviar solicitud</button><div id="reqProdMsg"></div></div><div class="section-head"><h2>${profile.role==='admin'?'Solicitudes recientes':'Mis solicitudes'}</h2></div><div id="myProductRequests" class="list"><div class="empty">Cargando…</div></div>`;const r=profile.role==='admin'?await query('product_requests','*','order=created_at.desc&limit=30'):await query('product_requests','*',`requested_by=eq.${profile.id}&order=created_at.desc&limit=30`);const rows=r.data||[];$('#myProductRequests').innerHTML=rows.map(x=>`<div class="row"><div class="line"><div><div class="title">${esc(x.proposed_name)}</div><div class="subtext">${esc(x.proposed_unit)} · ${dt(x.created_at)}${x.notes?' · '+esc(x.notes):''}</div></div><span class="badge ${x.status==='approved'?'green':x.status==='rejected'?'red':'amber'}">${esc((x.status||'pending').toUpperCase())}</span></div></div>`).join('')||'<div class="empty">Sin solicitudes.</div>';$('#sendProdRequest').onclick=async()=>{const b=$('#sendProdRequest');b.disabled=true;b.textContent='Enviando…';const rr=await rpc('create_product_request',{p_name:$('#reqProdName').value.trim(),p_unit:$('#reqProdUnit').value,p_notes:$('#reqProdNotes').value.trim()||null});b.disabled=false;b.textContent='Enviar solicitud';if(rr.error)return msg($('#reqProdMsg'),rr.error);msg($('#reqProdMsg'),'Solicitud enviada para aprobación.',true);setTimeout(()=>renderProductRequest(),350)}}
async function rejectProductRequest(id){const r=await rpc('reject_product_request',{p_request_id:id});if(r.error)return alert(r.error);await loadAll(true);renderModule('alerts')}
function renderModule(name){activeModule=name;if(name==='contractors')renderContractors();if(name==='alerts')renderAlerts();if(name==='reports')renderReports();if(name==='product-request')renderProductRequest();if(name==='audit'&&profile.role==='admin')renderAudit();if(name==='admin'&&profile.role==='admin')renderAdmin(activeAdminTab)}
const _renderAlerts=renderAlerts;renderAlerts=function(){_renderAlerts();const nt=D.notifications.filter(x=>!x.read_at);if(nt.length){const head=$('#moduleContent .section-head');if(head){const b=document.createElement('button');b.className='btn sm soft';b.textContent='Marcar avisos leídos';b.onclick=markAllNotifications;head.appendChild(b)}}if(profile.role==='admin'){$$('[data-approve-product]').forEach(x=>{const wrap=x.parentElement;if(wrap&&!wrap.querySelector('[data-reject-product]')){const b=document.createElement('button');b.className='btn sm danger';b.dataset.rejectProduct=x.dataset.approveProduct;b.textContent='Rechazar';b.onclick=()=>rejectProductRequest(b.dataset.rejectProduct);wrap.appendChild(b)}})}};
$('#fabExit').onclick=()=>movementForm('exit');
$('#stockSearch').oninput=renderStock;$('#stockWarehouse').onchange=renderStock;$('#stockState').onchange=renderStock;$('#moveSearch').oninput=renderMoves;$('#moveType').onchange=renderMoves;$('#moveWarehouse').onchange=renderMoves;$('#moveBarge').onchange=renderMoves;$('#moveContractor').onchange=renderMoves;$('#moveFrom').onchange=renderMoves;$('#moveToDate').onchange=renderMoves;
