// AVH — OC profesional: cabecera fija, sin solapamientos y PDF archivado.
(function(){
  const safe=s=>typeof esc==='function'?esc(String(s??'')):String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
  const dateOnly=v=>{if(!v)return'—';try{return new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString('es-PY')}catch{return String(v)}};
  const paymentText=v=>{const t=String(v||'').trim();if(!t)return'Según presupuesto';if(/^cred\.?$/i.test(t))return'Crédito';if(/^cont\.?$/i.test(t))return'Contado';return t};
  const PDF_SOURCE='generated_professional_header_v6_no_logo';
  const st=document.createElement('style');
  st.textContent=`
    .po-sheet.po-polished{padding:0;border:1px solid #dbe6df;border-radius:16px;overflow:hidden;background:#fff;color:#16231c;box-shadow:0 8px 28px rgba(15,54,34,.06)}
    .po-polished .po-top{display:grid;grid-template-columns:minmax(0,1fr) 210px;gap:28px;align-items:center;padding:23px 26px 18px;border-bottom:3px solid #174c35}
    .po-polished .po-buyer{min-width:0}.po-polished .po-eyebrow{font-size:9px;font-weight:900;letter-spacing:.09em;color:#718178;margin-bottom:6px}.po-polished .po-buyer-name{font-size:14px;font-weight:950;color:#174c35;line-height:1.22;overflow-wrap:anywhere}.po-polished .po-buyer-meta{font-size:10.5px;color:#61736a;line-height:1.45;margin-top:5px;overflow-wrap:anywhere}
    .po-polished .po-doc{min-width:0;text-align:right;border-left:1px solid #dfe8e2;padding-left:18px}.po-polished .po-doc-title{font-size:21px;font-weight:950;line-height:1.05}.po-polished .po-doc-number{font-size:17px;color:#174c35;font-weight:950;margin-top:6px}.po-polished .po-doc-date{font-size:11px;color:#687970;margin-top:5px}
    .po-polished .po-body{padding:18px 26px 24px}.po-polished .po-info-grid{display:grid;grid-template-columns:1.12fr .88fr;gap:12px}.po-polished .po-info-card{border:1px solid #dfe8e2;border-radius:12px;padding:13px;background:#fcfefd}.po-polished .po-info-title{font-size:10px;font-weight:900;letter-spacing:.08em;color:#6c7e74;margin-bottom:7px}.po-polished .po-info-card b{font-size:14px}.po-polished .po-info-line{font-size:12px;line-height:1.55;color:#34493e;margin-top:3px}
    .po-polished .po-order-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:10px}.po-polished .po-kv{border:1px solid #e1e9e4;border-radius:10px;padding:9px 10px}.po-polished .po-kv span{display:block;font-size:9px;font-weight:850;letter-spacing:.05em;color:#708077;text-transform:uppercase}.po-polished .po-kv b{display:block;font-size:12px;margin-top:4px;line-height:1.35}
    .po-polished .po-items{width:100%;border-collapse:collapse;margin-top:18px}.po-polished .po-items th{background:#174c35;color:#fff;font-size:10px;letter-spacing:.03em;padding:10px 8px;text-align:left}.po-polished .po-items td{padding:10px 8px;border-bottom:1px solid #e4ebe7;font-size:12px;vertical-align:top}.po-polished .po-items th:nth-child(n+3),.po-polished .po-items td:nth-child(n+3){text-align:right}.po-polished .po-item-code{font-size:10px;color:#718178;margin-top:3px}.po-polished .po-sum{display:flex;justify-content:flex-end;margin-top:14px}.po-polished .po-total-box{min-width:260px;background:#f0f7f3;border:1px solid #ccdfd3;border-radius:11px;padding:13px 15px;display:flex;align-items:center;justify-content:space-between;gap:18px}.po-polished .po-total-box span{font-size:11px;font-weight:850;color:#64766c}.po-polished .po-total-box b{font-size:21px;color:#174c35}.po-polished .po-foot{margin-top:17px;padding-top:12px;border-top:1px solid #e1e9e4;font-size:10px;line-height:1.55;color:#687970}
  `;
  document.head.appendChild(st);
  const purchases=()=>D.purchases||[],items=id=>(D.purchaseItems||[]).filter(x=>x.purchase_id===id),company=id=>(D.purchaseCompanies||[]).find(x=>x.id===id)||{},supplier=id=>(D.suppliers||[]).find(x=>x.id===id)||{},product=id=>(D.products||[]).find(x=>x.id===id)||{};
  const orderDoc=id=>(D.purchaseDocuments||[]).filter(x=>x.purchase_id===id&&x.kind==='order').sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0))[0]||null;
  function purchaseByPo(po){const key=String(po||'').trim();return purchases().find(x=>String(x.po_number||'').trim()===key)||null}
  function purchaseFromModal(){const direct=document.querySelector('#modalBody .po-no')?.textContent?.trim();if(direct){const p=purchaseByPo(direct);if(p)return p}const detail=document.querySelector('#detailOpenPo')?.textContent||'';const m=detail.match(/OC-[A-Z0-9-]+/i);if(m)return purchaseByPo(m[0]);return null}
  function dest(p){if(p.destination_type==='warehouse')return p.warehouse_name||(typeof whName==='function'?whName(p.warehouse_id):'Depósito');if(p.destination_type==='barge')return p.barge_number?`Barcaza ${p.barge_number}`:(p.barge_id&&typeof bargeNo==='function'?`Barcaza ${bargeNo(p.barge_id)}`:'Barcaza / proyecto');return p.destination_text||'Entrega directa'}
  function polishedHtml(p){const c=company(p.company_id),s=supplier(p.supplier_id),rows=items(p.id),total=rows.reduce((a,x)=>a+num(x.quantity)*num(x.unit_price),0),project=p.barge_number?`Barcaza ${p.barge_number}`:(p.barge_id&&typeof bargeNo==='function'?`Barcaza ${bargeNo(p.barge_id)}`:'—');return `<div class="po-top"><div class="po-buyer"><div class="po-eyebrow">COMPRADOR</div><div class="po-buyer-name">${safe(c.legal_name||c.name||p.company_name||'')}</div><div class="po-buyer-meta">${c.tax_id?`RUC ${safe(c.tax_id)}<br>`:''}${c.address?safe(c.address)+'<br>':''}${[c.phone,c.email].filter(Boolean).map(safe).join(' · ')}</div></div><div class="po-doc"><div class="po-doc-title">ORDEN DE COMPRA</div><div class="po-doc-number po-no">${safe(p.po_number||'OC')}</div><div class="po-doc-date">Fecha: ${dateOnly(p.po_generated_at||p.created_at)}</div></div></div><div class="po-body"><div class="po-info-grid"><div class="po-info-card"><div class="po-info-title">PROVEEDOR</div><b>${safe(s.name||p.supplier_name||'Proveedor sin definir')}</b><div class="po-info-line">${s.tax_id?`RUC ${safe(s.tax_id)}`:'RUC no registrado'}${s.phone?` · Tel. ${safe(s.phone)}`:''}</div></div><div class="po-info-card"><div class="po-info-title">ENTREGA</div><b>${safe(dest(p)||'—')}</b><div class="po-info-line">${p.expected_date?`Fecha prevista: ${dateOnly(p.expected_date)}`:'Plazo: según presupuesto / coordinación'}</div></div></div><div class="po-order-grid"><div class="po-kv"><span>Presupuesto / referencia</span><b>${safe(p.source_document_number||p.order_reference||'—')}</b></div><div class="po-kv"><span>Condición de pago</span><b>${safe(paymentText(p.payment_terms))}</b></div><div class="po-kv"><span>Moneda</span><b>${safe(p.currency||'PYG')}</b></div><div class="po-kv"><span>Proyecto</span><b>${safe(project)}</b></div></div><table class="po-items"><thead><tr><th>Descripción técnica</th><th>Unidad</th><th>Cantidad</th><th>Precio unit.</th><th>Total</th></tr></thead><tbody>${rows.map(x=>{const pr=product(x.product_id);return `<tr><td><b>${safe(x.description)}</b>${pr.sku?`<div class="po-item-code">Código AVH: ${safe(pr.sku)}</div>`:''}</td><td>${safe(x.unit)}</td><td>${fmt(x.quantity)}</td><td>${money(x.unit_price,p.currency)}</td><td><b>${money(num(x.quantity)*num(x.unit_price),p.currency)}</b></td></tr>`}).join('')}</tbody></table><div class="po-sum"><div class="po-total-box"><span>TOTAL ORDEN DE COMPRA</span><b>${money(total,p.currency)}</b></div></div><div class="po-foot"><b>Contacto de Compras:</b> Gabriel Ortega${c.phone?` · ${safe(c.phone)}`:' · 0971 800 829'}${c.email?` · ${safe(c.email)}`:' · gortega@astillerovh.com'}<br>Esta Orden de Compra corresponde al presupuesto/referencia indicado y queda registrada en AVH junto con su documentación y recepción.</div></div>`}
  function polishCurrentModal(){const sheet=document.querySelector('#modalBody .po-sheet');if(!sheet||sheet.dataset.polished==='1')return;const p=purchaseFromModal();if(!p)return;sheet.classList.add('po-polished');sheet.dataset.polished='1';sheet.innerHTML=polishedHtml(p);const status=document.querySelector('#modalBody .po-status');if(status)status.textContent=(p.status==='ordered'||p.purchase_confirmed_at)?'COMPRADO / PEDIDO':'OC GENERADA · PENDIENTE DE CONFIRMAR COMPRA'}
  async function signedUrl(path){const encoded=String(path||'').split('/').map(encodeURIComponent).join('/');const r=await request(`/storage/v1/object/sign/purchase-documents/${encoded}`,{method:'POST',body:{expiresIn:180}});if(r.error)throw Error(r.error);const u=r.data?.signedURL||r.data?.signedUrl;if(!u)throw Error('No pude obtener el PDF archivado.');return /^https?:/.test(u)?u:`${API}/storage/v1${u.startsWith('/')?u:'/'+u}`}
  async function downloadStored(doc,p){const u=await signedUrl(doc.file_path),r=await fetch(u);if(!r.ok)throw Error('No pude descargar la OC archivada.');const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=doc.file_name||`${p.po_number||'Orden-de-Compra'}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2500)}
  async function fastDownload(p,btn){const old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Descargando…'}try{const doc=orderDoc(p.id);if(doc?.source===PDF_SOURCE)return await downloadStored(doc,p);if(window.AVHSmartPurchase?.downloadPurchaseOrderPdf){await window.AVHSmartPurchase.downloadPurchaseOrderPdf(p.id);await loadAll(true);return}if(doc)return await downloadStored(doc,p);throw Error('Esta compra todavía no tiene PDF de OC archivado.')}finally{if(btn){btn.disabled=false;btn.textContent=old||'⬇ Descargar OC en PDF'}}}
  document.addEventListener('click',e=>{const btn=e.target?.closest?.('#poDownload,#detailDownloadPo');if(!btn)return;const p=purchaseFromModal();if(!p)return;e.preventDefault();e.stopImmediatePropagation();fastDownload(p,btn).catch(err=>alert(err.message||String(err))) },true);
  const observer=new MutationObserver(()=>polishCurrentModal());observer.observe(document.body,{childList:true,subtree:true});document.addEventListener('click',()=>setTimeout(polishCurrentModal,0),true);window.AVHPOPolish={polishCurrentModal,fastDownload};
})();